Dynamic MVAU
Xilinx/finn pull request #1253
Opened 2024-12-12 16:47 UTC by azizb-xlnx

2024-12-16 07:18 UTC, preusser requested changes
Thanks, @azizb-xlnx & @d-kor!
Please, review comments made for RTL code.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load.sv
> +localparam integer SIMD_BITS = (SIMD == 1) ? 1 : $clog2(SIMD);
These should all be `int unsigned`.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load.sv
> +    input   logic  ivld,
Make indentation consistent.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load.sv
> +state_wr_t state_wr_C, state_wr_N;
Initialize all registers - in almost all cases to their reset state.
This is the `_C` signals only though. Do not initialize combinational ones, i.e., `_N` signals here.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load.sv
> +state_rd_t state_rd_C, state_rd_N;
Initialize registers.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load.sv
> +// -- Signals
Unspecific category. It should read "wires"/"nets" or "registers".

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load_tmp.sv
> +    input   logic  ivld,
Inconsistent indentation.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load_tmp.sv
> +localparam integer SIMD_BITS = (SIMD == 1) ? 1 : $clog2(SIMD);
`int unsigned` all the way.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load_tmp.sv
> +state_wr_t state_wr_C, state_wr_N;
Initialize regs.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mv_matrix_load_wide.sv
> +// Copyright (C) 2024, Advanced Micro Devices, Inc. All rights reserved.
Somehow these modules feel repetitive. Why do they all need to exist?

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mvu_dyn_axi.sv
> +	int unsigned SIMD,
Inconsistent indentation.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/mvu_dyn_axi.sv
> +endmodule
Please. fix these file endings. Git actually flags them reliably in a commit.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/ram_p_c.sv
> +    parameter ADDR_BITS = 10,
`int unsigned` for the numeric parameters.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/ram_p_c.sv
> +  localparam DEPTH = 2**ADDR_BITS;
`localparam int unsigned`.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/ram_p_c.sv
> +    parameter RAM_TYPE = "block"
Use `RAM_STYLE` for consistency throughout the designs.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/ram_p_c.sv
> +  (* ram_style = RAM_TYPE *) reg [DATA_BITS-1:0] ram[DEPTH];
`RAM_STYLE = RAM_STYLE`.

2024-12-16 07:18 UTC, preusser commented on finn-rtllib/mvu/ram_p_c.sv
> +  reg [DATA_BITS-1:0] a_data_reg = 0;
`reg` -> `logic`.

2024-12-16 10:52 UTC, maltanar requested changes
Most of my comments are made with what would be needed to get this into FINN dev branch as a clean integration, while some others (e.g. for folded shapes and for convert_to_hw_layers) are also critical for enablement in the custom branch.

2024-12-16 10:52 UTC, maltanar commented on src/finn/custom_op/fpgadataflow/rtl/dynmvau_rtl.py
> +            folded_input_shape = tuple(vecs + [nf, pe])
I'm not sure this is right. e.g. if my dyn matmul has 1x12x32x128 as the B input, I would expect the folded shape here to be [1, 12, 32, 128//PE, PE] whereas the current impl here would give [1, 32, 128//PE, PE]. there needs to be something derived from numInputVectors here - possibly with the last element (N_VECTORS?) dropped

2024-12-17 10:43 UTC, azizb-xlnx commented on tests/fpgadataflow/test_fpgadataflow_dynamic_mvau.py
> +    return model
updating to 1xHxMxK inputs

2024-12-17 17:37 UTC, azizb-xlnx commented on src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
> +        return ""
regarding the dtype = "", that's something i was testing that sneaked in, I've removed it.

2024-12-18 07:40 UTC, azizb-xlnx commented on tests/fpgadataflow/test_fpgadataflow_dynamic_mvau.py
> +def test_fpgadataflow_dynamic_mvau_cppsim(M, N, K, pe, simd, A_dtype, B_dtype):
yup. removing.

2024-12-18 08:29 UTC, azizb-xlnx commented on src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
> +            "N_VECTORS": ("i", True, 0), # Height of Matrix A
Agreed, N_VECTORS is redundant, removing.

2024-12-18 08:31 UTC, azizb-xlnx commented on src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
> +            "N_VECTORS": ("i", True, 0), # Height of Matrix A
Regarding naming, plan was to make as little churn to existing code as possible for eoy goal, then rename things in the next pass. so I'm going to leave it as is for now.

2024-12-18 08:35 UTC, azizb-xlnx commented on src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
> +        mvau_w_init = mvau_w_init_list[0] if mvau_w_init_list else None
I agree, to simplify things we decided to use the initializer==None  as indicator for dyn mvau. I've tagged these areas with #TODOs to come back in the next pass to apply correct flags.

2024-12-18 08:41 UTC, azizb-xlnx commented on src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
> +            inp_B = np_helper.to_array(mvau_w_init)
this is actually an existing code :)

2024-12-18 09:05 UTC, azizb-xlnx commented on src/finn/custom_op/fpgadataflow/rtl/dynmvau_rtl.py
> +            f.write(template_wrapper.replace("$FORCE_BEHAVIORAL$", str(0)))
Will introduce pyxsi in the next pass.

2024-12-18 09:08 UTC, azizb-xlnx commented on src/finn/custom_op/fpgadataflow/rtl/dynmvau_rtl.py
> +        if mem_mode == "internal_decoupled":
the mem_mode is something i will have to come back to, currently it is set to external to expose the input interface for second input

2024-12-18 09:09 UTC, azizb-xlnx commented on src/finn/transformation/fpgadataflow/convert_to_hw_layers.py
> +                            N_VECTORS=mm_in_shape[1], # Height of the input tensor A for dynamic MVAU
removed N_VECTORS attribute.

2024-12-18 12:19 UTC, maltanar commented
Thanks @azizb-xlnx - with your latest changes I think this is good to go for the EoY targets. Not sure what is going on for the failing quicktest, as it passed when I tried to run `end2end_mobilenet` tests individually so I wouldn't worry too much about that one.

2024-12-18 14:16 UTC, merged