RTL ConvInpGen: Dynamic FM dimensions
Xilinx/finn pull request #688
Opened 2022-09-22 07:45 UTC by fpjentzsch

Exposes control registers to enable re-programming of the RTL SWG during runtime. The RTL component is generated once for the largest required configuration in terms of buffer depth (e.g., the largest FM dimensions) and can then adapt to **arbitrary changes in FM dimension (stride and dilation also possible)** as long as they fit inside the buffer. Kernel, bitwidth, and folding configuration remain constant.

2022-10-24 12:34 UTC, fpjentzsch commented
Hi @maltanar, @preusser,
This is ready to merge from my side. I already incorporated Yaman's changes to this component from https://github.com/Xilinx/finn/pull/699, which can be merged after this PR.

2022-10-25 05:59 UTC, preusser requested changes
Thanks, @fpjentzsch!
Please, see the inline comments.

2022-10-25 05:59 UTC, preusser commented on finn-rtllib/swg/swg_template_default.sv
> +            default: addr_incr = 0;
Is it meaningful to have a `default` case here?

2022-10-25 05:59 UTC, preusser commented on finn-rtllib/swg/swg_template_default.sv
> +        case (State)
Consider making this a `unique case` unless there is a good reason not to.

2022-10-25 05:59 UTC, preusser commented on finn-rtllib/swg/swg_template_default_dynamic.sv
> +        case (State)
Consider `unique case`.

2022-10-25 05:59 UTC, preusser commented on finn-rtllib/swg/swg_template_default_dynamic.sv
> +            default: addr_incr = 0;
Check whether `default` is meaningful here.

2022-10-25 05:59 UTC, preusser commented on finn-rtllib/swg/swg_template_default_dynamic.sv
> +    always_comb begin : blkTail
A conditional `assign` appears to be easier to grasp:
```
assign  tail_incr =
  tail_incr_inner_condition? 1 :
  Counter_loop_w >= 0?       Cfg_incr_tail_w :
  Counter_loop_h >= 0?       Cfg_incr_tail_h :
  /* else */                 Cfg_incr_tail_last;
```

2022-10-27 11:28 UTC, fpjentzsch commented on finn-rtllib/swg/swg_template_default.sv
> +            default: addr_incr = 0;
No, I just tried to avoid an unintentional latch. A `unique case` is a much better solution, thanks for the suggestion!

2022-10-27 11:33 UTC, fpjentzsch commented on finn-rtllib/swg/swg_template_default_dynamic.sv
> +    always_comb begin : blkTail
I agree.

2022-11-03 09:53 UTC, preusser approved these changes

2023-01-31 09:50 UTC, merged