RTL ConvInpGen: Window parallelism
Xilinx/finn pull request #714
Opened 2022-12-01 08:19 UTC by fpjentzsch

### Overview:
Adds a new implementation style to output all window elements (pixels) simultaneously, thus enabling full SIMD (`= kernel_width * kernel_height * channels`) unfolding of the following MVAU/VVAU layer.

Previously, this was supported only for the 1D case via the HLS function `ConvolutionInputGenerator_1D_parallel`.

Includes basic readthedocs documentation.

### Depends on:

- [x] https://github.com/Xilinx/finn/pull/688 (is included)
- [x] https://github.com/Xilinx/finn/pull/723

2023-03-06 14:31 UTC, preusser requested changes

2023-03-06 14:31 UTC, preusser commented on finn-rtllib/swg/swg_template_parallel.sv
> +#(
Please, type these numeric parameters appropriately, e.g. as `int unsigned`.

2023-03-06 14:31 UTC, preusser commented on finn-rtllib/swg/swg_template_parallel.sv
> +module $TOP_MODULE_NAME$_ram_buffer
Please, justify name differentiation and old Verilog style as above.

2023-03-06 14:31 UTC, preusser commented on finn-rtllib/swg/swg_template_parallel.sv
> +module $TOP_MODULE_NAME$_wb
Please, justify old Verilog style. Name differentiation okay.

2023-03-06 14:31 UTC, preusser commented on finn-rtllib/swg/swg_template_parallel.sv
> +    int  BIT_WIDTH,
It appears that most or all of these parameters should actually be `int unsigned`.

2023-03-06 14:31 UTC, preusser commented on finn-rtllib/swg/swg_template_parallel.sv
> +    always_ff @(posedge ap_clk) begin
There should either be a reset to `0` matching the initialization value or an initialization to `'x`.

2023-03-14 14:21 UTC, fpjentzsch commented on finn-rtllib/swg/swg_template_parallel.sv
> +module $TOP_MODULE_NAME$_reg_buffer
You are right. I moved this module (now `swg_reg_buffer`), along with `swg_controller`, `swg_cyclic_buffer_addressable`, `swg_ram_buffer`, into a new source file ("swg_common.sv") that is independent of the code generation and thus identical for every layer.

2023-03-14 14:25 UTC, fpjentzsch commented
Thanks Thomas! I incorporated your comments. @auphelia this also addresses your concern about the controller that is shared between both implementation styles.

2023-03-17 10:14 UTC, preusser requested changes

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +reg [WIDTH-1:0] data [DEPTH-1:0];
`logic` rather than `reg` would be preferred.

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +for (genvar e=0; e<DEPTH; e=e+1)
`e++` rather than `e=e+1` preferred.

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +        for (integer i=DEPTH-1; i>0; i=i-1)
Please, use the 2-value type `int` rather than 4-valued `integer`.
`i--` would be preferred over `i=i-1`.

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +reg [WIDTH-1:0] out_reg;
`logic` preferred over `reg`.

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +integer addr_w, addr_r;
Please, use a type with an exact bit width, e.g. `logic [$clog2(DEPTH)-1:0]` for the range 0:DEPTH-1.
Also, please, initialize in correspondance to reset state.

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +    if (RST == 1'b0) begin
Low polarity of reset should be visible in name, e.g., `rst_n`.

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +always @(posedge CLK) begin
Prefer more specific `always_ff`.

2023-03-17 10:14 UTC, preusser commented on finn-rtllib/swg/swg_common.sv
> +(*ram_style=RAM_STYLE*) reg [WIDTH-1:0] ram [DEPTH-1:0];
`logic` rather than `reg`.

2023-03-28 12:05 UTC, preusser approved these changes

2023-04-19 15:27 UTC, auphelia approved these changes
Thanks for the PR, @fpjentzsch!

2023-04-19 16:26 UTC, merged