Refactoring of RTL MVAU/VVAU
Xilinx/finn pull request #995
Opened 2024-03-04 11:05 UTC by mmrahorovic

[WIP]
PR combines the previously closed PRs: PR #976 , PR #975 and PR #794.

2024-03-07 15:05 UTC, auphelia requested changes
Thanks @mmrahorovic , here already a few comments for the PR so far. Please also bring your PR up-to-date with the refactoring branch.

2024-03-07 15:15 UTC, auphelia commented on src/finn/custom_op/fpgadataflow/rtl/matrixvectoractivation_rtl.py
> +            raise Exception("cppsim not possible for RTL MVAU, please set exec_mode to rtlsim")
Please add defined behavior if cppsim is selected.

2024-03-07 15:33 UTC, mmrahorovic commented on finn-rtllib/mvu/mvu_4sx4u.sv
> +module mvu_4sx4u #(
Thanks! Will do!

2024-03-07 15:35 UTC, mmrahorovic commented on src/finn/transformation/fpgadataflow/specialize_layers.py
> +    act_width_in_range = (
Agree, done!

2024-03-15 14:36 UTC, mmrahorovic commented on src/finn/transformation/fpgadataflow/specialize_layers.py
> +    # Checks whether RTL-based MVU is supported
Thanks! I've added a few comments now.

2024-03-15 14:36 UTC, mmrahorovic commented on src/finn/custom_op/fpgadataflow/rtl/matrixvectoractivation_rtl.py
> +# (optional) input 2 is the thresholds tensor, shape (o_size, n_thres)
Cleaned up, thanks! :)

2024-03-15 14:37 UTC, mmrahorovic commented on src/finn/custom_op/fpgadataflow/rtl/matrixvectoractivation_rtl.py
> +            self.get_nodeattr("resType") != "lut"
Makes most sense indeed, I'll change it.

2024-03-15 14:37 UTC, mmrahorovic commented on src/finn/custom_op/fpgadataflow/rtl/matrixvectoractivation_rtl.py
> +                elif in_ind > 2:
Good catch, should be indeed in_ind>1! Thanks :)

2024-03-15 14:38 UTC, mmrahorovic commented on src/finn/custom_op/fpgadataflow/rtl/matrixvectoractivation_rtl.py
> +    def get_verilog_top_filename(self):
Both functions are not used indeed -- as discussed I'll leave it out.

2024-03-15 16:50 UTC, merged